version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vulnerable_app
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: